name: Bol Monitor (Self‑Hosted)

on:
  schedule:
    - cron: "*/15 * * * *"   # elke 15 minuten
  workflow_dispatch:          # handmatig starten via Actions-tab

permissions:
  contents: write             # nodig om state.json te committen

jobs:
  check:
    runs-on: self-hosted      # <— belangrijk: jouw eigen runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright (Chromium)
        run: npx playwright install chromium

      # Snelle sanity check of de Discord-webhook
      - name: Test Discord webhook (ping)
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" ^
            -H "Content-Type: application/json" ^
            -d "{\"content\":\"✅ Self-hosted runner kan posten naar Discord (ping)\"}" ^
            "%DISCORD_WEBHOOK_URL%"
        shell: cmd
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      # Draai je monitor één keer (leest watchlist.json)
      - name: Run monitor once
        run: npm run check
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          CHECK_INTERVAL_MINUTES: 30
          CHECK_JITTER_SECONDS: 10
          TIMEOUT_MS: 20000

      # Bewaar status voor volgende runs (alleen als gewijzigd)
      - name: Commit state changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add state.json
          git diff --cached --quiet || (git commit -m "chore: update state [skip ci]" && git push)

      # Downloadbare debug: HTML + screenshots van bezochte productpagina's
      - name: Upload debug artifacts (html + screenshots)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bol-debug
          path: artifacts/**
